# Generated by Django 5.2.7 on 2025-10-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('score', models.IntegerField()),
                ('link', models.URLField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stars', models.IntegerField()),
                ('url', models.URLField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
